name: Custom Windows Client Generator

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: true
        type: string
      zip_url:
        description: 'URL to zip of json'
        required: true
        type: string
      enableMetricsCPU:
        description: 'Enable CPU metrics'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      enableMetricsRAM:
        description: 'Enable RAM metrics'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      enableMetricsDisk:
        description: 'Enable Disk metrics'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Write metrics to file
        run: |
          echo "enable_metrics_cpu=${{ github.event.inputs.enableMetricsCPU }}" >> custom.txt
          echo "enable_metrics_ram=${{ github.event.inputs.enableMetricsRAM }}" >> custom.txt
          echo "enable_metrics_disk=${{ github.event.inputs.enableMetricsDisk }}" >> custom.txt
      - name: Upload custom.txt
        uses: actions/upload-artifact@v4
        with:
          name: metrics-config
          path: custom.txt
